# Generated by Django 5.2.4 on 2025-07-09 16:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم اللاعب')),
                ('position', models.CharField(choices=[('حارس مرمى', 'حارس مرمى'), ('مدافع', 'مدافع'), ('وسط', 'وسط'), ('مهاجم', 'مهاجم')], max_length=20, verbose_name='المركز')),
                ('birth_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2003), django.core.validators.MaxValueValidator(2014)], verbose_name='سنة الميلاد')),
                ('city', models.CharField(choices=[('الرياض', 'الرياض'), ('جدة', 'جدة'), ('مكة المكرمة', 'مكة المكرمة'), ('المدينة المنورة', 'المدينة المنورة'), ('الدمام', 'الدمام'), ('الخبر', 'الخبر'), ('الظهران', 'الظهران'), ('الأحساء', 'الأحساء'), ('الطائف', 'الطائف'), ('جازان', 'جازان'), ('بريدة', 'بريدة'), ('تبوك', 'تبوك'), ('القطيف', 'القطيف'), ('خميس مشيط', 'خميس مشيط'), ('حفر الباطن', 'حفر الباطن'), ('الجبيل', 'الجبيل'), ('الخرج', 'الخرج'), ('أبها', 'أبها'), ('حائل', 'حائل'), ('نجران', 'نجران'), ('ينبع', 'ينبع'), ('صبيا', 'صبيا'), ('الباحة', 'الباحة'), ('سكاكا', 'سكاكا'), ('عرعر', 'عرعر'), ('عنيزة', 'عنيزة'), ('القريات', 'القريات'), ('أخرى', 'أخرى')], max_length=50, verbose_name='المدينة')),
                ('nationality', models.CharField(choices=[('سعودي', 'سعودي'), ('أجنبي', 'أجنبي'), ('مواليد السعودية', 'مواليد السعودية')], max_length=20, verbose_name='الجنسية')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('previous_clubs', models.TextField(blank=True, help_text='اكتب أسماء الأندية السابقة وعدد السنوات', verbose_name='الأندية السابقة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('video', models.FileField(blank=True, help_text='مقطع فيديو يعرض مهارات اللاعب (بحد أقصى 120 ثانية)', null=True, upload_to='player_videos/', verbose_name='مقطع فيديو')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'لاعب',
                'verbose_name_plural': 'اللاعبون',
                'ordering': ['-created_at'],
            },
        ),
    ]
